[project]
name = "webx"
version = "0.1"
description = "WebX Browser"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "portalocker>=3.2.0",
    "pyside6>=6.10.0",
    "requests>=2.32.5",
    "watchdog>=6.0.0",
]
